name: 'dart_todo'
version: 0.0.1
description: A sample todo-list app written in Dart.
author: Matteo Rosati <mrosati@h-art.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  rpc: '^0.5.6'

transformers:
- dart_to_js_script_rewriter
